name: Deploy Development

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout ğŸ›
        uses: actions/checkout@master

      - name: Build Docker Image ğŸ³
        run: sudo docker build -f Dockerfile . -t php-dev:latest

      - name: Remove exist container ğŸº
        run: sudo docker rm -f php-dev || true

      - name: Ensure Docker Network Created ğŸŒ
        run: |
          if ! sudo docker network inspect backend > /dev/null 2>&1; then
            sudo docker network create backend
          fi

      - name: Run Docker Container ğŸº
        run: sudo docker run -p 8082:80 --network backend --name php-dev -d php-dev:latest
