name: React CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Install dependencies
        #working-directory: react-app
        run: npm install

      - name: Run tests
        #working-directory: react-app
        run: npm test -- --watchAll=false

      - name: Build React app
        #working-directory: react-app
        run: npm run build

      - name: Build Docker image
        run: docker build -f Dockerfile -t react-app:latest .
      
      - name: Ensure Docker Network Created ğŸŒ
        run: |
          if ! docker network inspect backend > /dev/null 2>&1; then
             docker network create backend
          fi

      - name: Stop and remove existing Docker container 
        run: |
          if docker ps -a --format '{{.Names}}' | grep -Eq '^react$'; then
            docker stop react
            docker rm react
          fi  

      - name: Run Docker container ğŸƒ
        run:  docker run -d -p 3001:80 --name react --network backend react-app:latest
